# Generated by Django 5.0.3 on 2024-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_delete_user_management_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_management_model',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
