# Generated by Django 5.0.3 on 2024-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_management_model',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_management_model',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
