# Generated by Django 5.0.3 on 2024-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_data_management_model_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rec_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
