# Generated by Django 5.0.3 on 2024-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_location_rec_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
