# Generated by Django 5.0.3 on 2024-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='rec_no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
